### PR TITLE
Include val/rdy ifcs and re-organize lib directory

### PR DESCRIPTION
**Pull request by tancheng**
- Include val/rdy ifcs and re-organize lib directory.
 - Include https://github.com/tancheng/PyOCN as sub-module.
   - [ ] Leverage CGRA's lib in PyOCN's ifcs.

### CODE REVIEW

**Comment by tancheng** [comment]
@rp15 @yuqisun @yo96 @yyan7223 @MeowMJ plz be aware that I re-organize the lib directory hierarchy and now it contains both `val/rdy` and `en/rdy` ifcs. The change is due to we wanna integrate VectorCGRA with https://github.com/tancheng/PyOCN (@cbatten for awareness), and they use different versions of PyMTL3 (VectorCGRA relies on `en/rdy` in a particular commit: https://github.com/tancheng/pymtl3.1/tree/yo-struct-list-fix supported by @yo96 while PyOCN relies on `val/rdy`, and both `en/rdy` and `val/rdy` don't co-exist in the specific PyMTL3 version), so I include the `val/rdy` in this PR and will change the import path of the included PyOCN to use them (instead of relying on its own PyMTL3 version's [stdlib/stream/ifcs.py](https://github.com/pymtl/pymtl3/blob/master/pymtl3/stdlib/stream/ifcs.py)).
 - Ideally, both should be updated to the latest PyMTL3 and just use `val/rdy`, which could be the long-term goal.
 - For the integration of VectorCGRA and PyOCN, I would keep `en/rdy` within CGRA tiles, while leveraging `val/rdy` to interconnect multiple CGRAs via PyOCN.

**Review by yyan7223 — COMMENTED** [review]
This is DALAO, much work done in only few days...
But there are too many files changed to review them in a short time, how about we check its functionality in the subsequent use of those functions.

**Comment by tancheng** [comment]
Not really. Most changes are copy-pasted. And PyOCN is also created by @yo96 and me.

True, I am including PyOCN's tests gradually in this PR (WIP). Thanks!

**Comment by tancheng** [comment]
Well, I have not yet completed this PR. I will create a new branch anyways.

**Comment by yuqisun** [comment]
> Well, I have not yet completed this PR. I will create a new branch anyways.

Ah! Sorry I just forgot to switch branch and deleted my change from master then, not sure why merged this.

**Comment by tancheng** [comment]
No worry~!

**Pull request merged**
